//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.OrmLanguage
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "simpleorm";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"OrmLanguage";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID OrmLanguageDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(OrmLanguageCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID OrmLanguageExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(OrmLanguageCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewOrmLanguageExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(OrmLanguageCommandSetId), 0x0001);
	
		// Package identifier
		public const string OrmLanguagePackageId = "673435e5-6a48-4569-b3b6-7a7ca61bb1d2";
		
		// Editor factory identifier
		public const string OrmLanguageEditorFactoryId = "b7394ff9-2081-4b2d-bcaf-43e465f31314";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string OrmLanguageModelExplorerToolWindowId = "fc64633f-a0d4-45dc-a5c2-924fcfb0e9e1";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.OrmLanguage
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string OrmLanguageCommandSetId = "8fa6312d-5282-4261-9438-810a4c01580b";
	}
}